version: '3.8'

services:
  api:
    container_name: credit-card-api-container-debug
    build:
      context: .
      dockerfile: CreditProposal.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "32769:32769"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      #ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:32769"
    depends_on:
      - credit-proposal-sql-server
      # - rabbitmq # Adicionado para garantir que o RabbitMQ esteja disponível
    networks:
      - my-network
    volumes:
      - ~/.vsdbg:/remote_debugger  # Para o depurador (Permite gravação)

  credit-proposal-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: credit-proposal-sql-server-container
    environment:
      SA_PASSWORD: Docker1206
      ACCEPT_EULA: Y
    ports:
      - "1434:1433" # Mapeando a porta externa 1434 para a interna 1433
    networks:
      - my-network

networks:
  my-network:
    external: true # Para poder compartilhar o rabbitmq
